language: node_js
node_js:
    - "4.3"
script:
    - npm install
    - npm test
    - npm run deploy
env:
    global:
        # Upload to riffraff
        - secure: key here
        - secure: key here
cache:
    directories:
        - node_modules
